<section>
    <div class="jumbotron">
        <h1>$title$</h1>
        <p>$message$</p>

        <div class="row">
            <div class="col-lg-7">
            	<form action="/redirect" method="post">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">URL</span>
                    <input id="index_text_url" name="url" type="text" class="form-control" placeholder="http://github.com">
                    <span class="input-group-btn">
                        <button id="index_button_go" class="btn btn-default" type="submit">Go!</button>
                    </span>
                </div>
                <!-- /input-group -->
                </form>
            </div>
            <!-- /.col-lg-6 -->
        </div>
        <!-- /.row -->
    </div>

</section>