<section>
  <h2>Using <a href="https://github.com/MTDdk/jawn" target="_blank">jawn</a></h2>
  <p class="lead">Take a look at the different functionality by using the tabs above</p>

  <p style="margin-top: 30px;">
 If you have started the server in <var>development</var> mode, try to edit the HTML templates in
 <code>webapp/views/</code>
    and update the corresponding page
  </p>
  
  
  $if(flash)$
  <p>$flash.message$</p>
  $endif$
</section>