<section>
  <div class="panel panel-default">
    <div class="panel-heading">Miscellaneous paths:</div>
    <div class="panel-body">
      <ul>
        <li><code>/test/{type}</code> <small>(default: text)</small>
          <ul>
            <li><a href="test/json">/test/json</a></li>
            <li><a href="test/xml">/test/xml</a></li>
            <li><a href="test/text">/test/text</a></li>
          </ul>
        </li>
        <li><a href="/random">/random</a> - random movie from the database in json</li>
        <li><a href="/image">/image</a> - getting a file via the controller</li>
        <li><a href="/shutdown" onclick="javascript:jQuery.get('/shutdown');return false;">/shutdown</a> - shut down the server</li>
      </ul>
    </div>
  </div>
</section>